### ISSUE TITLE
Feature Request: "Embrava Blynclight" Integration

### ISSUE THREAD

**Issue by milander** [josephdadams/beacon#1]
Really loving this DIY Call Light you have created. 

However for my application, I require a much bigger light "blinker"

Will it be difficult to integrate Beacon with Embrava's Blynclight? 
https://www.amazon.com/Embrava-Blynclight-Standard/dp/B07FRX1DK4

I dug around and found this: https://github.com/X-Guard/blync-plus-core
Not sure if it helps.

Thanks for your consideration

**Comment by josephdadams** [comment]
yes, I have already been working on this. I do not have a timeline for when I will finish it since I am doing it in my spare time.

**Comment by josephdadams** [comment]
I just added support for the Kuando Busylight: https://www.amazon.com/dp/B019WQXWA2

It is similar in size to the Embrava Blynclight Standard. I could never get my Blynclight to behave properly so I abandoned it.
