### ISSUE TITLE
Feature Request: Beacon Light as Camera Tally Light

### ISSUE THREAD

**Issue by cmweeks0510** [josephdadams/beacon#2]
Hi, I came across your beacon app in conjunction with bitfocus companion. I am using it to control my black magic switcher and would really like to use the beacon app as a tally light for my cameras. I looked to see if I could control the beacon with a feedback option for my buttons, but I didn't see beacon as an option there.

Thanks for your work on this.

**Comment by josephdadams** [comment]
Using beacon's robust API, or, with the beacon module in Companion, you should have no problem doing this. Use Triggers within companion to accomplish this. The Trigger can monitor a feedback state or variable from your ATEM and then trigger an action to beacon accordingly.
